<?php

namespace Kaymorey\PortfolioBackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends EntityRepository
{
	public function getWorksByCategory($category)
    {
        $qb = $this->createQueryBuilder('w')
            ->leftJoin('w.category', 'c')
            ->addSelect('c');
        $qb->where('c.id = :category')
            ->setParameter('category', $category);
            
        return $qb->getQuery()->getResult();
    }
}
